// FILE WAS GENERATED BY gowasm-gen-import, DO NOT EDIT!
//
// Source file: syscall_js.go
// Generated at: 2023-04-07 15:20:13.271474 +0200 CEST m=+0.000970418

#include "textflag.h"

// func stat(name string, out *inode, cb int)
TEXT ·stat(SB), NOSPLIT, $0
  CallImport
  RET

// func readDir(name string, out []inode, cb int)
TEXT ·readDir(SB), NOSPLIT, $0
  CallImport
  RET

// func readFile(f inode, out []byte, cb int)
TEXT ·readFile(SB), NOSPLIT, $0
  CallImport
  RET

// func writeFile(name string, data []byte, cb int)
TEXT ·writeFile(SB), NOSPLIT, $0
  CallImport
  RET

// func makeDir(name string, cb int)
TEXT ·makeDir(SB), NOSPLIT, $0
  CallImport
  RET

// func unlink(name string, cb int)
TEXT ·unlink(SB), NOSPLIT, $0
  CallImport
  RET

