// FILE WAS GENERATED BY gowasm-gen-import, DO NOT EDIT!
//
// Source file: syscall_js.go

#include "textflag.h"

// func stat(name string, out *inode, cb int)
TEXT ·stat(SB), NOSPLIT, $0
  CallImport
  RET

// func readDir(name string, out *[]inode, cb int)
TEXT ·readDir(SB), NOSPLIT, $0
  CallImport
  RET

// func readFile(fid uint64, out *[]byte, cb int)
TEXT ·readFile(SB), NOSPLIT, $0
  CallImport
  RET

// func writeFile(name string, data []byte, cb int)
TEXT ·writeFile(SB), NOSPLIT, $0
  CallImport
  RET

// func makeDir(name string, cb int)
TEXT ·makeDir(SB), NOSPLIT, $0
  CallImport
  RET

// func unlink(name string, cb int)
TEXT ·unlink(SB), NOSPLIT, $0
  CallImport
  RET

