version: "2"
run:
  tests: false
formatters:
  exclusions:
    paths:
      - "pkg/worker/"
      - "cmd/webworker/"
      - "web/"

linters:
  exclusions:
    rules:
      - text: ".Close` is not checked"
        linters:
          - errcheck
    paths:
      - "pkg/worker/"
      - "cmd/webworker/"
      - "web/"
