run:
  tests: false
  skip-dirs:
    - pkg/worker
    - cmd/webworker
issues:
  exclude-rules:
    - path: 'internal/gowasm/(.+)\.go'
      linters:
        - typecheck
linters:
  disable:
    # workaround for: 'panic: load embedded ruleguard rules: rules/rules.go:13: can't load fmt'
    - fmt