// FILE WAS GENERATED BY gowasm-gen-import, DO NOT EDIT!
//
// Source file: callback_js.go

#include "textflag.h"

// func registerCallbackHandler(fn js.Func)
TEXT ·registerCallbackHandler(SB), NOSPLIT, $0
  CallImport
  RET

