// FILE WAS GENERATED BY gowasm-gen-import, DO NOT EDIT!
//
// Source file: callback_js.go
// Generated at: 2023-04-07 15:20:13.520176 +0200 CEST m=+0.000891209

#include "textflag.h"

// func registerCallbackHandler(fn js.Func)
TEXT ·registerCallbackHandler(SB), NOSPLIT, $0
  CallImport
  RET

