// FILE WAS GENERATED BY gowasm-gen-import, DO NOT EDIT!
//
// Source file: entrypoint_js.go

#include "textflag.h"

// func registerWorkerEntrypoint(methods []string, handler js.Func)
TEXT ·registerWorkerEntrypoint(SB), NOSPLIT, $0
  CallImport
  RET

