// FILE WAS GENERATED BY gowasm-gen-import, DO NOT EDIT!
//
// Source file: stdio_js.go

#include "textflag.h"

// func wasmConsoleWrite(fd int, data []byte)
TEXT ·wasmConsoleWrite(SB), NOSPLIT, $0
  CallImport
  RET

