// FILE WAS GENERATED BY gowasm-gen-import, DO NOT EDIT!
//
// Source file: worker_js.go

#include "textflag.h"

// func registerWorkerEntrypoint(handler js.Func, methods []string)
TEXT ·registerWorkerEntrypoint(SB), NOSPLIT, $0
  CallImport
  RET

