// FILE WAS GENERATED BY gowasm-gen-import, DO NOT EDIT!
//
// Source file: downloads_js.go

#include "textflag.h"

// func onPackageManagerEvent(e packageManagerEvent)
TEXT ·onPackageManagerEvent(SB), NOSPLIT, $0
  CallImport
  RET

