// FILE WAS GENERATED BY gowasm-gen-import, DO NOT EDIT!
//
// Source file: runner_js.go

#include "textflag.h"

// func onProgramEvalStateChange(state EvalState, msg string)
TEXT ·onProgramEvalStateChange(SB), NOSPLIT, $0
  CallImport
  RET

