// FILE WAS GENERATED BY gowasm-gen-import, DO NOT EDIT!
//
// Source file: writer_js.go

#include "textflag.h"

// func logWrite(level uint8, data []byte)
TEXT ·logWrite(SB), NOSPLIT, $0
  CallImport
  RET

