import React from 'react'
import ReactDOM from 'react-dom'
import * as serviceWorkerRegistration from './serviceWorkerRegistration'
import { initializeIcons } from './icons'
import { App } from './App'
import './index.css'

// Polyfills
import 'core-js/actual/promise/all-settled'
import 'core-js/actual/array/flat-map'

initializeIcons()

// eslint-disable-next-line import/no-named-as-default-member
ReactDOM.render(<App />, document.getElementById('root'))

// v1 shipped a ServiceWorker generated by CRA which always was unreliable.
// This wersion doesn't ship SW but still old registrations should manually removed.
serviceWorkerRegistration.unregister()
