import React from 'react'
import { createRoot } from 'react-dom/client'
import * as serviceWorkerRegistration from './serviceWorkerRegistration'
import { initializeIcons } from './icons'
import { App } from './App'
import './index.css'

// Polyfills
import 'core-js/actual/promise/all-settled'
import 'core-js/actual/array/flat-map'

initializeIcons()

const rootElement = document.getElementById('root')

if (!rootElement) {
  throw new Error('Root element not found')
}

createRoot(rootElement).render(<App />)

// v1 shipped a ServiceWorker generated by CRA which always was unreliable.
// This wersion doesn't ship SW but still old registrations should manually removed.
serviceWorkerRegistration.unregister()
